name: change commit count
on:
  push:
    branches:
      - 'uat'

env:
  GITHUB_TOKEN: ${{ secrets.TOKEN }}

jobs:
  push_and_deploy:
    name: change count
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      
      - name: commit
        run: |
          git clone https://OsamaWohlig:${{ secrets.TOKEN }}@github.com/OsamaWohlig/commit-count.git
          cd commit-count
          git config --global user.email "osama.patel@wohlig.com"
          git config --global user.name "OsamaWohlig"
          cat test.txt
          commit_count=$(<commit_count.txt)
          new_commit_count=$((commit_count + 50))
          echo "$new_commit_count" > commit_count.txt
          echo "Commit count updated to: $new_commit_count"
          cat test.txt
          git add .
          git remote set-url origin https://OsamaWohlig:${{ secrets.TOKEN }}@github.com/OsamaWohlig/commit-count.git
          git commit -m "test"
          git push --set-upstream origin main
