name: change commit count
on:
  push:
    branches:
      - 'uat'

env:
  GITHUB_TOKEN: ${{ secrets.TOKEN }}

jobs:
  push_and_deploy:
    name: change count
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      
      - name: commit
        run: |
          git clone https://OsamaWohlig:${{ secrets.TOKEN100 }}@github.com/OsamaWohlig/commit-count.git
          git config --unset-all http.https://github.com/.extraheader
          git config --global user.email "osama.patel@wohlig.com"
          git config --global user.name "OsamaWohlig"
          cd commit-count
          count = `expr ${{secrets.COUNT}} + 50`
          echo count
          cat > new-test.txt << EOL
          hello i am devops
          my commit count is : $count
          thank you
          EOL 
          sed -i 's/${{ secrets.COUNT }}/${{ secrets.COUNT }}+50/g' test.txt
          cat test.txt